name: End to end test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          cache: "pip"

      - name: Install deps
        run: |
          pip install -r requirements.txt -r requirements_dev.txt

      - name: Run test suite
        run: |
          python -m pytest -s tests/e2e -v
